const ACTIONS = {
    JOIN: "JOIN",
    JOINED: "JOINED",
    DISCONNECTED: "DISCONNECTED",
    LEAVE: "LEAVE",
    SYNC_CODE: "SYNC_CODE",
    TYPING: "TYPING",
    CODE_CHANGE: "CODE_CHANGE",
    CURSOR_MOVED: "CURSOR_MOVED",
    SEND_MESSAGE: "SEND_MESSAGE",
    RAISE_HAND: "RAISE_HAND",
    WHITEBOARD_UPDATE: "WHITEBOARD_UPDATE",
};

module.exports = ACTIONS;