const ACTIONS = {
    JOIN: "JOIN",
    JOINED: "JOINED",
    DISCONNECTED: "DISCONNECTED",
    LEAVE: "LEAVE",
    SYNC_CODE: "SYNC-CODE",
    CODE_CHANGE: "CODE-CHANGE",
    CURSOR_MOVED: "CURSOR_MOVED",
    SEND_MESSAGE: "SEND-MESSAGE",
    WHITEBOARD_UPDATE: "WHITEBOARD_UPDATE",
};

module.exports = ACTIONS;