const ACTIONS = {
    JOIN: "JOIN",
    JOINED: "JOINED",
    DISCONNECTED: "DISCONNECTED",
    CODE_CHANGE: "CONDE-CHANGE",
    SYNC_CODE: "SYNC-CODE",
    LEAVE: "LEAVE",
    SEND_MESSAGE: "SEND-MESSAGE",
    WHITEBOARD_UPDATE: 'WHITEBOARD_UPDATE',
};

module.exports = ACTIONS;